### ISSUE TITLE
Not able to run in Kubernetes

### ISSUE THREAD

**Issue by strange2x** [PureStorage-OpenConnect/pure-fa-openmetrics-exporter#180]
I have been trying to get a simple deployment of the exporter in Kubernetes and I have tried the following manifest file to get it up and running. 

The pod is coming up and it is showing as running, but when am trying to go to /metrics endpoint or something am getting the following error

<img width="509" alt="Image" src="https://github.com/user-attachments/assets/8c4effde-6bd9-43bd-bb7a-de17e5ebf639" />

Is there something that am missing? 

Please find the attached manifest file that I have used for the deployment. 

Help is appreciated.
Thanks

```yaml
# https://kubernetes.io/docs/concepts/workloads/controllers/deployment/
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fa-exporter-test
  namespace: fa
  labels:
    app: fa-exporter-test
spec:
  selector:
    matchLabels:
      app: fa-exporter-test
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: fa-exporter-test
    spec:
      # initContainers:
        # Init containers are exactly like regular containers, except:
          # - Init containers always run to completion.
          # - Each init container must complete successfully before the next one starts.
      containers:
      - name: fa-exporter-test
        image: quay.io/purestorage/pure-fa-om-exporter:v1.0.23
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
        livenessProbe:
          tcpSocket:
            port: 9490
          initialDelaySeconds: 5
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
          periodSeconds: 10
        # readinessProbe:
        #   httpGet:
        #     path: /_status/healthz
        #     port: 9490
        #   initialDelaySeconds: 5
        #   timeoutSeconds: 2
        #   successThreshold: 1
        #   failureThreshold: 3
        #   periodSeconds: 10
        # env:
        # - name: DB_HOST
        #   valueFrom:
        #     secretKeyRef:
        #       name: fa-exporter-test
        #       key: MSSQL_SA_PASSWORD
        ports:
        - containerPort: 9490
          name: fa
        volumeMounts:
        - name: fa-secret-volume
          mountPath: /etc/pure-fa-om-exporter/
      volumes:
        - name: fa-secret-volume
          secret:
            secretName: fa-test-secret
      restartPolicy: Always
```
