### ISSUE TITLE
API key as url parameter

### ISSUE THREAD

**Issue by 4xoc** [PureStorage-OpenConnect/pure-fa-openmetrics-exporter#2]
The old pure_exporter had the option to set the api token as url parameter which allowed the value to be set via label mapping. As a result, there was only one prometheus scrape job for all arrays and not one job per array as this new version enforces. That's because one can set the parameter in the targets list (see below). Any chance to add url parameter back again? Scaling with more arrays is otherwise tricky and breaks many workflows (like silencing an entire job because of maintenance etc). Here's an example of how we currently use it with the old exporter that unfortunately no longer works.

prometheus.yml
```
scrape_configs:
  - job_name: 'pure'
    honor_labels: true
    metrics_path: /metrics/flasharray
    scrape_interval: 10s
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_endpoint
      - source_labels: [__pure_apitoken]
        target_label: __param_apitoken
      - source_labels: [__address__]
        target_label: instance
        # trim fqdn to short name
        regex: '^(.+)\.example\.com$'
      - target_label: __address__
        replacement: localhost:9491
    file_sd_configs:
      - files:
        - /etc/prometheus/targets/pure.yml
```
/etc/prometheus/targets/pure.yml
```
- targets: [ pure1.example.com ]
  labels:
    __pure_apitoken: aaaa-bbb-ccc-ddd-eee
- targets: [ pure2.example.com ]
  labels:
    __pure_apitoken: aaaa-bbb-ccc-eee-ddd
```
